### ISSUE TITLE
PHP 8 Compatibility: Function libxml_disable_entity_loader() is deprecated

### ISSUE THREAD

**Issue by jaredrhodes** [rootinc/laravel-saml2-middleware#5]
Need to get upstream changes. See https://github.com/onelogin/php-saml/issues/453

**Comment by OPVL** [comment]
Also facing this issue, I've forked for now to get PHP8 support & update OneLogin deps. Hasn't introduced any issues as far as I can tell, integrating with azure ad saml2, laravel 8+ & php8

**Comment by danieltjewett** [comment]
@OPVL feel free to submit a PR with the changes.
